### ISSUE TITLE
Splitting up article data with firestore and realtime db

### ISSUE THREAD

**Issue by arunstop** [arunstop/scuffed-blogger#13]
We can split up article data from only using firestore to use both firestore and realtime database.

Reasons : 
- Article's content is gonna be too big, and that's already good in firestore since it doesn't care about size
- Realtime databse is better for searchability.

I guess we can clone article title, description and other stuff to RTDB while maintaining the true data in firestore?.

**Comment by scuffed-developer** [comment]
Okay! Seems like a good idea!

**Comment by arunstop** [comment]
Already solved #14
