### ISSUE TITLE
Add some route protection when user is not logged in

### ISSUE THREAD

**Issue by scuffed-developer** [arunstop/scuffed-blogger#16]
Hey @arunstop please add some route protection when users are not logged in, since right now i can just access /write and perform write, yes it would be denied by the configured rules of the firebase. But it is still not good for the UX and DX

**Comment by arunstop** [comment]
Okay will do, but not right now.

**Comment by arunstop** [comment]
It is on #18

**Comment by arunstop** [comment]
done #18
