### ISSUE TITLE
RTDB's Order by doesn't seem to work

### ISSUE THREAD

**Issue by arunstop** [arunstop/scuffed-blogger#21]
@scuffed-developer said that firebase rtdb's `orderByValue` is not working. Had some talks with him that i agree it is not that big of a deal (YET). So, we'll save it for later. 

for reference : [This issue.](https://github.com/arunstop/scuffed-blogger/pull/20#discussion_r939568064)

**Comment by arunstop** [comment]
FIXED in #23. Great job :tada: @scuffed-developer

**Comment by scuffed-developer** [comment]
Phew :sweat_smile:
