### ISSUE TITLE
User/posts page showing 'no result with keyword' when the user has no posts

### ISSUE THREAD

**Issue by scuffed-developer** [arunstop/scuffed-blogger#32]
![image](https://user-images.githubusercontent.com/110107130/189340884-9b473b07-cb12-4757-99af-b5b8483f9178.png)

**Comment by scuffed-developer** [comment]
should show that user has no post and show, `write article` button

**Comment by arunstop** [comment]
Will do after i go in to Windows! My dear variant

**Comment by arunstop** [comment]
Done and dusted in #35
