### ISSUE TITLE
Refactoring

### ISSUE THREAD

**Issue by scuffed-developer** [arunstop/scuffed-blogger#8]
# TODO : 

- Refactor some function, using tree's top > down pattern
for example, instead of addArticle we should use articleAdd
if you are confused, just think about when you want to locate a file in a disk
you would go /folder/subfolder/file.

**Comment by arunstop** [comment]
Ok, will create a new branch

**Comment by arunstop** [comment]
Now you bit something you cannot chew, my dear variant :angry:

**Comment by scuffed-developer** [comment]
Well, i can click it, and i can assign you, my dear variant. Just wait till someday i will replace you. :rofl:

**Comment by arunstop** [comment]
Created a pull request! Pls review @scuffed-developer 

#9

**Comment by scuffed-developer** [comment]
Will check!
